### PR TITLE
Upgrade to Julia1.6.0

### PR DESCRIPTION
**Pull request by cemyr**
Seems to work around 10x faster with the new version, using the GPU

### CODE REVIEW

**Comment by Dsantra92** [comment]
Thanks for the contribution!! 🤗  However I would like to suggest some minor changes before merging it.
1. There is no need for two notebooks, we can keep only the updated(1.6) notebook, discarding the previous version.
2. You can clear the the output of the first shell, just to make the notebook more clutter free. The screenshot size can be adjusted a bit. Refer to the 1.5.3 for doing so.
3. The screenshot can be placed in the misc folder, just to the directory organized.

**Comment by cemyr** [comment]
Ok, I agree of course one NB is better, thanks for your positive feedback and swift reply, will complete it asap, thanks for this cool project 🤩

**Comment by cemyr** [comment]
Hi there, made adjustments to the notebook to unclutter the output, moved the image and deleted the other notebooks. 
Pls review and merge if you agree, thanks.

**Comment by Dsantra92** [comment]
Thanks for this PR!!

**Pull request merged**
